language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "project-zarvis"
    token:
      secure:  "uA7BC98SFTb+h0/WZ+oJjDdZunoUl+hie2havCkqLYeeta4ptHhH4/nVxINvZDTwONIsUaGChxO0MPm9bEmBMrmj8SBUY9nY8cezLTN0mNyvcO0XN0EtBW3L5ny3ft2vsmgdIaW7gYo+ViyxG6S2g+tWp4SpoEl2YtLTWQhIh6cw/1bnm+qV1+cVF2IC6i5lOA5GhEmlGg9rqacdWbIlJK1dr/57CAnRTXE6GO87bCkIo54yG3SRjpen4CCeckdfnx3W4xJDETDoZ9xCI9B5LeVV6BsPKHLtOcHQzJBsPsGxPSzGqogoFYL7UrWquqrQKVcnFx3zAwS+ZDJrY/6WrJ+SG+q4as95NO/iDyvAObQVSlfy0F0KSoF7vzJNzJRJOgekDyzYmzpVKAI2uyEmNjHAysrZjG6iR/4nMdyEczMbZyAaSAx/NFr2xrgOdN6rKZb85Grp7BBnnwdlQBdbWdiC66fIgMEPkETEXdkWosROU/YIwLsIa3xq7zCgr1tiLuEACxOUjjHsNt3K0Wqm0UId0TFEIE5aU2bpyauaREv6v6wakYzrZ1CDbmHKSc5bQeJw3o8No+ev3RDVkVU8Bj1v6U9X5ASytfVFEhpSChNvoD8M0hNQgVeGHa/cGHjb9TfbCo2riyw2CU9kZ1OHHxJMMvyGVV1TndQXI69628A="


jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
