language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "p-zarvis"
    token:
      secure: "I1qDD1AnUBImkHAAfyMf3NxBDfppelw4UNL8N7LSmpsvHCOvikru2h4XeIT4oCAS+5nEt5Br0UsvAWBe7G5EeIkJ6scu8Wr4S/NKWLyyQ+RuTJKw3wXShPZnunYF7pcIl/VJ7sR1Sa/AmSRpYJwvLCp37Al/fhI0maNKREJr0rSCM94yT1Te5n6WIM84wdTrS6E2SCCuxQFQ2APWTA2b4fJyo8q3LpIanhIFjzd30iPlm00MVLRFf3yjyTQi7S+FPQK+HK0Sz08lz/lAZ3bYFyVaL/ntYGi/HnqsEElZirIqtn5TGpwIPwyONDgkqMweF4+u9Yz268SjCPfEirP3QXwubSE5LRolsybDa9GpalFiMhtK8cGAOoUonnLWTCeBsdJBeVk4debsjOErZiAe1uEs19gRyABbXpxdiPpEizbJkR9zxI2gAQ6HFMIvmNQ9QSp0ORl1Z+XGJhryfyWvEQO+kdztLv/59qpZWs4TL84ow5qrhwKo8antEU6VtjJJLzv9QSUsRGExXUopz2UhxRiAU7H1ajktYsYNzuIEYE9SgWQ5WMrv85dCrsvCRfVPQdnhiBg0sDC03yExVuMPp/UF7inJlC4nFuvV3pOFjAlpQWmZVunLt34Bb9dWpxcfnV1kYkWnjhBNg9DpaN/4hoUD3nFD4bIyTzPgWxTpOuc="

    branches:
    - master

jdk:
- openjdk8
script:
  - "gradle sonarqube"

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"

group: stable
dist: trusty
os: linux
    
