language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "project-zarvis"
    token:
      secure: "npdwu2hcuFUWvol2eGvVdNF6uNqHFQ/NX8+MayVNGDZbVye9ejbVJ9lrAzXV/TMbWo/vJlJ5UnmK/hZ+7Z+sfHfNCKQCJ6zVdmg71822UFMcruMw5ea5katRWqFG49Efk+xXnUPWDNSAvzNaDyHoiICHUG6b96p3zPp+E76TsPmWaKDa6UOQOFQufJ3nIOPm9fMnsb+dTKPE+zuFtihlB0ySf/t0MS3/n/IvtWemDF0o/gU2MSqVQR9dAs7cqH31vAIVPM8sGAwpuZbwwVeHLEuhfHmcDAGa6XnhZZVghnz1uyFAbaxncmD1YMivau3fzhtC3YErCj+qWyFWeRIPw2NajjlsmELFxMhb0DDB5tGea7NEfda03rBYQDl1c/SniBw6VcG7EteJhnvPo8Htb0B67kvR3K3aLts+SWHOSChW9HLwlJXLGwJFKZxTeFLD7N4asA4RTdQUX5SnMGG8Vk24Jb+ei225/qTSuby9IUfsdzDkZufanWcEeD17Cw58QNfRj3n+/8BmXzBLTNqD6Rvu/V1vSgvzHxdTB650k6hExitwhn4O0Ewxn4iy0ULHH9V6Hi2GcDsI0KRF5tZUGYmA7T8wpCZ7VTCkj5myDbJmnxKVoTlQBYjI2Vkxg/NwExSXCzo6LZKRE66tb78ewL/ny64MzEPiBZRLDn+1Mps="
    branches:
    - master
    - develop
script:
    - "gradle sonarqube"

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - "$.gradle"

group: stable
dist: trusty
os: linux

