language: java
jdk:
    - openjdk8
group: stable
dist: trusty
os: linux
secure: "LvO9JZ45+2g5e0XJpGrcJyH5IbF7ob+oJKkvxNjyhfSowQmmg/IvXA5iBzqMOWu5Ku70qL2uIceW1PYlg14JAIGGkTPdeF3h/ZJZuZ+x9Mgl3kI5s0PdxOmPTo8ICrqoS1qMqtdDccHBTNz6jTLi6eO5gxop/4zjhDyRugqvq34j9oyM4h6bukt9bGQhcG8UnNpJWfwUt7oBdY5dxc6hhbNbFRQmX9EForioYBklz+iwtXpCVPRi90lJ2U29Cr+TL5ikJw7GIgQ4kA+rQ7pmM2t8jmUTuMN2if6+p1jknV5ZCoYMLMQXnEGEXY8f5qffvmbw485wjzMmIJYci5Ep31FeXhB5c/iBSBhIwPiEXLALOnBN2QIbgToaXqCM5f9DFVOdUMAwusXgHDzyxfd0tab0VA0LQ0NjQ5sdvlu7bWjsYwad+Y5Um5Yt1slz5ab43Tbcib6Bkcszrplu3tRM/Ju2v7kEEf3Gf8j3RPGaLVnd/PfNcoOkDdB5+sKrQ0N7OhB9PsSlatOwy2h06QBeRjUuoGc0LdWY3J5INTRijfLvSLn6Qa7eL1msQlaZiJy/MxFDJCQsu45D3qJVbS/BA/RPA4TptrZN71Tdraq8/Uy2cUn+X0qgt/NakjcoR/tbhobOz2u9kCxMpK9aT3VvTrnII2gDuXfnoZNCvNCRjSY="
