language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: project-zarvis
    token:
      secure: ${SONAR_TOKEN}
    github_token:
      secure: ${GITHUB_TOKEN}
    branches:
    - master
    - develop
script:
- "gradle sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - "$.gradle"
group: stable
dist: trusty
os: linux

