language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "zarvis-project"
    token:
      secure: ${SONAR-TOKEN}

    branches: # The branches monitored by sonarqube
      - master
jdk:
  - openjdk8

script:
  - "gradle sonarqube"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
